apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: develop-execution-app-{{PR_NUMBER}}
  name: develop-execution-app-{{PR_NUMBER}}
  namespace: agile-pr-review
spec:
  replicas: 1
  selector:
    matchLabels:
      app: develop-execution-app-{{PR_NUMBER}}
  template:
    metadata:
      labels:
        app: develop-execution-app-{{PR_NUMBER}}
      annotations:
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/agent-inject-status: 'update'
        vault.hashicorp.com/role: 'internal-app'
        vault.hashicorp.com/agent-inject-secret-develop-execution-app: 'internal/data/develop-execution-app'
        vault.hashicorp.com/agent-inject-template-develop-execution-app: |
          {{- with secret "internal/data/develop-execution-app" -}}
            {{- range $key, $value := .Data.data }}
              export {{ $key }}={{ $value }}
            {{- end }}
          {{- end -}}
    spec:
      containers:
        - name: develop-execution-app-{{PR_NUMBER}}
          image: registry.digitalocean.com/karpatkey/execution-app:pr{{DOCKER_TAG}}
          imagePullPolicy: Always
          command: ['/bin/sh', '-c']
          args: ['source /vault/secrets/develop-execution-app && node server.js']
          ports:
            - containerPort: 3000
              protocol: TCP
          env:
            - name: AUTH0_BASE_URL
              value: '{{PR_SUBDOMAIN}}'

            - name: DATA_WAREHOUSE_ENV
              value: development

            - name: MODE
              value: development

            - name: PULLEY_URL
              value: 'http://localhost:4000'

        - name: pulley
          image: registry.digitalocean.com/karpatkey/pulley:main
          imagePullPolicy: Always
          env:
            - name: ETHEREUM_RPC_ENDPOINT
              value: 'https://rpc.mevblocker.io'
            - name: GNOSIS_RPC_ENDPOINT
              value: 'https://rpc.gnosischain.com'

---
apiVersion: v1
kind: Service
metadata:
  name: develop-execution-app-{{PR_NUMBER}}
  namespace: agile-pr-review
spec:
  ports:
    - port: 3000
      name: one
      protocol: TCP
      targetPort: 3000

  selector:
    app: develop-execution-app-{{PR_NUMBER}}
