version: '3'
services:
  app:
    build:
      context: .
    container_name: app
    env_file:
      - .env  # Specify the path to your .env file
    ports:
      - "3000:3000"
    # Add other configurations as needed for your custom app

  anvil_ethereum:
    image: ghcr.io/foundry-rs/foundry:latest
    container_name: anvil
    # Remember to update the KEY with your own key
    entrypoint: /bin/sh -c "anvil --accounts 15 -f https://eth-mainnet.g.alchemy.com/v2/KEY --port 8546 --host 0.0.0.0"
    ports:
      - "8546:8546"
  anvil_gnosis:
    image: ghcr.io/foundry-rs/foundry:latest
    container_name: anvil
    # Remember to update the KEY with your own key
    entrypoint: /bin/sh -c "anvil --accounts 15 -f https://few-delicate-snowflake.xdai.quiknode.pro/KEY --port 8547 --host 0.0.0.0"
    ports:
      - "8547:8547"
