version: '3'
services:
  dev:
    build:
      context: .
      target: dev
    container_name: dev
    env_file:
      - .env # Specify the path to your .env file
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/.next
    profiles:
      - dev

  prod:
    build:
      context: .
    container_name: prod
    env_file:
      - .env # Specify the path to your .env file
    ports:
      - '3000:3000'
    profiles:
      - prod

  pulley:
    build:
      context: ../pulley
    container_name: pulley
    env_file:
      - .env
    ports:
      - '4000:4000'
