services:
  dev:
    build:
      context: .
      target: dev
    container_name: dev
    environment:
      - VAULT_SIGNER_URL=http://host.docker.internal:8200/v1/ethereum
      - VAULT_SIGNER_TOKEN=root
    env_file:
      - .env # Specify the path to your .env file
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/.next
    profiles:
      - dev

  prod:
    build:
      context: .
    container_name: prod
    environment:
      - VAULT_SIGNER_URL=http://host.docker.internal:8200/v1/ethereum
      - VAULT_SIGNER_TOKEN=root
    env_file:
      - .env # Specify the path to your .env file
    ports:
      - '3000:3000'
    profiles:
      - prod

  rolesapi:
    build:
      context: ../roles_royce
      dockerfile: ../roles_royce/docker/Dockerfile.bots
    container_name: rolesapi
    environment:
      - APP=execution_app
    env_file:
      - .env
    ports:
      - '4001:8080'

  pulley:
    build:
      context: ../pulley
    container_name: app-pulley
    environment:
      - LOGGER_LEVEL=debug
      - PULLEY_SECONDS_TO_REFRESH=300
      - PULLEY_SECONDS_TO_IDLE_TIMEOUT=90
    env_file:
      - .env
    ports:
      - '4000:4000'

networks:
  default:
