version: '3'
services:
  dev:
    build:
      context: .
      target: dev
    container_name: dev
    environment:
      - VAULT_SIGNER_URL=http://host.docker.internal:8200/v1/ethereum
      - VAULT_SIGNER_TOKEN=root
    env_file:
      - .env # Specify the path to your .env file
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/.next
    profiles:
      - dev

  prod:
    build:
      context: .
    container_name: prod
    environment:
      - VAULT_SIGNER_URL=http://host.docker.internal:8200/v1/ethereum
      - VAULT_SIGNER_TOKEN=root
    env_file:
      - .env # Specify the path to your .env file
    ports:
      - '3000:3000'
    profiles:
      - prod

  pulley:
    build:
      context: ../pulley
    container_name: app-pulley
    environment:
      - LOGGER_LEVEL=info
    env_file:
      - .env
    ports:
      - '4000:4000'
