version: '3'
services:
  dev:
    build:
      context: .
      target: dev
    container_name: dev
    env_file:
      - .env # Specify the path to your .env file
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    profiles:
      - dev

  prod:
    build:
      context: .
    container_name: prod
    env_file:
      - .env # Specify the path to your .env file
    ports:
      - '3000:3000'
    profiles:
      - prod

  anvil_ethereum:
    image: ghcr.io/foundry-rs/foundry:latest
    container_name: anvil_ethereum
    # Remember to update the KEY with your own key
    entrypoint: /bin/sh -c "anvil --accounts 15 -f $ETHEREUM_RPC_ENDPOINT --port 8546 --host 0.0.0.0"
    ports:
      - '8546:8546'

  anvil_gnosis:
    image: ghcr.io/foundry-rs/foundry:latest
    container_name: anvil_gnosis
    # Remember to update the KEY with your own key
    entrypoint: /bin/sh -c "anvil --accounts 15 -f $GNOSIS_RPC_ENDPOINT --port 8547 --host 0.0.0.0"
    ports:
      - '8547:8547'
