version: '3'
services:
  app:
    build:
      context: .
    container_name: app
    env_file:
      - .env  # Specify the path to your .env file
    ports:
      - "3000:3000"
    # Add other configurations as needed for your custom app

  anvil:
    image: ghcr.io/foundry-rs/foundry:latest
    container_name: anvil
    entrypoint: /bin/sh -c "anvil --accounts 15 -f https://eth.llamarpc.com --port 8546 --host 0.0.0.0"
    ports:
      - "8546:8546"
