version: '3'
services:
  dev:
    build:
      context: .
      target: dev
    container_name: dev
    # environment:
    #   - WEB3SIGNER_ETHEREUM_URL=http://signer-ethereum:9000
    #   - WEB3SIGNER_GNOSIS_URL=http://signer-gnosis:9001
    env_file:
      - .env # Specify the path to your .env file
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/.next
    profiles:
      - dev

  prod:
    build:
      context: .
    container_name: prod
    # environment:
    #   - WEB3SIGNER_ETHEREUM_URL=http://signer-ethereum:9000
    #   - WEB3SIGNER_GNOSIS_URL=http://signer-gnosis:9001
    env_file:
      - .env # Specify the path to your .env file
    ports:
      - '3000:3000'
    profiles:
      - prod

  pulley:
    build:
      context: ../pulley
    container_name: app-pulley
    environment:
      - LOGGER_LEVEL=debug
    env_file:
      - .env
    ports:
      - '4000:4000'

  # web3signer_ethereum:
  #   image: consensys/web3signer:develop
  #   container_name: signer-ethereum
  #   ports:
  #     - '9000:9000'
  #   volumes:
  #     - ./key.yaml:/home/node/signer/keyFiles/key.yaml
  #     - ./config.yaml:/home/node/signer/config.yaml
  #   command:
  #     - '--config-file=/home/node/signer/config.yaml'
  #     - '--logging=DEBUG'
  #     - 'eth1'
  #     - '--chain-id=1'
  #
  # web3signer_gnosis:
  #   image: consensys/web3signer:develop
  #   container_name: signer-gnosis
  #   ports:
  #     - '9001:9001'
  #   volumes:
  #     - ./key.yaml:/home/node/signer/keyFiles/key.yaml
  #     - ./config.yaml:/home/node/signer/config.yaml
  #   command:
  #     - '--config-file=/home/node/signer/config.yaml'
  #     - '--logging=DEBUG'
  #     - '--http-listen-port=9001'
  #     - 'eth1'
  #     - '--chain-id=100'
