version: '3'
services:
  dev:
    build:
      context: .
      target: dev
    container_name: dev
    environment:
      - WEB3SIGNER_URL=http://signer:9000
    env_file:
      - .env # Specify the path to your .env file
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/.next
    profiles:
      - dev

  prod:
    build:
      context: .
    container_name: prod
    environment:
      - WEB3SIGNER_URL=http://signer:9000
    env_file:
      - .env # Specify the path to your .env file
    ports:
      - '3000:3000'
    profiles:
      - prod

  anvil_ethereum:
    image: ghcr.io/foundry-rs/foundry:latest
    container_name: anvil_ethereum
    entrypoint: /bin/sh -c "anvil --accounts 15 -f $ETHEREUM_RPC_ENDPOINT --port 8546 --host 0.0.0.0"
    ports:
      - '8546:8546'

  anvil_gnosis:
    image: ghcr.io/foundry-rs/foundry:latest
    container_name: anvil_gnosis
    entrypoint: /bin/sh -c "anvil --accounts 15 -f $GNOSIS_RPC_ENDPOINT --port 8547 --host 0.0.0.0"
    ports:
      - '8547:8547'

  web3signer:
    image: consensys/web3signer:develop
    container_name: signer
    ports:
      - '9000:9000'
    volumes:
      - ./key.yaml:/home/node/signer/keyFiles/key.yaml
      - ./config.yaml:/home/node/signer/config.yaml
    command:
      - '--config-file=/home/node/signer/config.yaml'
      - '--swagger-ui-enabled=true'
      - '--logging=DEBUG'
      - 'eth1'
      - '--chain-id=100'
