version: '3'
services:
  app:
    build:
      context: .
    container_name: app
    env_file:
      - .env # Specify the path to your .env file
    ports:
      - '3000:3000'
      - '3002:3002'

  anvil_ethereum:
    image: ghcr.io/foundry-rs/foundry:latest
    container_name: anvil_ethereum
    entrypoint: /bin/sh -c "anvil --accounts 15 -f $ETHEREUM_RPC_ENDPOINT --port 8546 --host 0.0.0.0"
    ports:
      - '8546:8546'

  anvil_gnosis:
    image: ghcr.io/foundry-rs/foundry:latest
    container_name: anvil_gnosis
    entrypoint: /bin/sh -c "anvil --accounts 15 -f $GNOSIS_RPC_ENDPOINT --port 8547 --host 0.0.0.0"

    ports:
      - '8547:8547'
