apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: develop-execution-app-{{PR_NUMBER}}
  name: develop-execution-app-{{PR_NUMBER}}
  namespace: agile-pr-review
spec:
  replicas: 1
  selector:
    matchLabels:
      app: develop-execution-app-{{PR_NUMBER}}
  template:
    metadata:
      labels:
        app: develop-execution-app-{{PR_NUMBER}}
      annotations:
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/agent-inject-status: 'update'
        vault.hashicorp.com/role: 'internal-app'
        vault.hashicorp.com/agent-inject-secret-envrc: 'internal/data/develop-execution-app'
        vault.hashicorp.com/agent-inject-template-envrc: |
          {{- with secret "internal/data/develop-execution-app" -}}
            {{- range $key, $value := .Data.data }}
              export {{ $key }}={{ $value }}
            {{- end }}
          {{- end -}}
    spec:
      containers:
        - name: develop-execution-app-{{PR_NUMBER}}
          image: registry.digitalocean.com/karpatkey/execution-app:pr{{DOCKER_TAG}}
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
              protocol: TCP
          env:
            - name: AUTH0_BASE_URL
              value: '{{PR_SUBDOMAIN}}'
          envFrom:
            - configMapRef:
                name: develop-execution-app-config-{{PR_NUMBER}}

        - name: pulley
          image: registry.digitalocean.com/karpatkey/pulley:main
          imagePullPolicy: Always
          env:
            - name: LOGGER_LEVEL
              value: debug

        - name: rolesapi
          image: registry.digitalocean.com/karpatkey/bots:feature-generic-execution-app-ad92d13
          env:
            - name: APP
              value: execution_app
            - name: PORT
              value: '4001'
          envFrom:
            - configMapRef:
                name: develop-execution-app-config-{{PR_NUMBER}}

---
apiVersion: v1
kind: Service
metadata:
  name: develop-execution-app-{{PR_NUMBER}}
  namespace: agile-pr-review
spec:
  ports:
    - port: 3000
      name: one
      protocol: TCP
      targetPort: 3000

  selector:
    app: develop-execution-app-{{PR_NUMBER}}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: develop-execution-app-config-{{PR_NUMBER}}
  namespace: agile-pr-review
data:
  VAULT_SIGNER_URL: 'http://develop-vault:8200/v1/ethereum'
  DATA_WAREHOUSE_ENV: development
  MODE: development
  PULLEY_URL: 'http://localhost:4000'
  ROLESAPI_URL: 'http://localhost:4001'
  BALANCERDAO_ETHEREUM_AVATAR_SAFE_ADDRESS: '0x0EFcCBb9E2C09Ea29551879bd9Da32362b32fc89'
  BALANCERDAO_ETHEREUM_DISASSEMBLER_ADDRESS: '0x60716991aCDA9E990bFB3b1224f1f0fB81538267'
  BALANCERDAO_ETHEREUM_ROLE: '1'
  BALANCERDAO_ETHEREUM_ROLES_MOD_ADDRESS: '0xd8dd9164E765bEF903E429c9462E51F0Ea8514F9'
  ENS_ETHEREUM_AVATAR_SAFE_ADDRESS: '0x4F2083f5fBede34C2714aFfb3105539775f7FE64'
  ENS_ETHEREUM_DISASSEMBLER_ADDRESS: '0xb423e0f6E7430fa29500c5cC9bd83D28c8BD8978'
  ENS_ETHEREUM_ROLE: '1'
  ENS_ETHEREUM_ROLES_MOD_ADDRESS: '0xf20325cf84b72e8BBF8D8984B8f0059B984B390B'
  GNOSISDAO_ETHEREUM_AVATAR_SAFE_ADDRESS: '0x849D52316331967b6fF1198e5E32A0eB168D039d'
  GNOSISDAO_ETHEREUM_DISASSEMBLER_ADDRESS: '0xb11ea45e2d787323dFCF50cb52b4B3126b94810d'
  GNOSISDAO_ETHEREUM_ROLE: '4'
  GNOSISDAO_ETHEREUM_ROLES_MOD_ADDRESS: '0x1cFB0CD7B1111bf2054615C7C491a15C4A3303cc'
  GNOSISDAO_GNOSIS_AVATAR_SAFE_ADDRESS: '0x458cD345B4C05e8DF39d0A07220feb4Ec19F5e6f'
  GNOSISDAO_GNOSIS_DISASSEMBLER_ADDRESS: '0x23bE4206Ae8bC9aC9cF6F7E99749C896ef75022f'
  GNOSISDAO_GNOSIS_ROLE: '4'
  GNOSISDAO_GNOSIS_ROLES_MOD_ADDRESS: '0x10785356E66b93432e9E8D6F9e532Fa55e4fc058'
  GNOSISLTD_ETHEREUM_AVATAR_SAFE_ADDRESS: '0x4971DD016127F390a3EF6b956Ff944d0E2e1e462'
  GNOSISLTD_ETHEREUM_DISASSEMBLER_ADDRESS: '0x6eD37375347B8A60883e62E50B012f813579254f'
  GNOSISLTD_ETHEREUM_ROLE: '4'
  GNOSISLTD_ETHEREUM_ROLES_MOD_ADDRESS: '0xEF4A73A20e2c6C6771C334e18a417A19Abb29c09'
  GNOSISLTD_GNOSIS_AVATAR_SAFE_ADDRESS: '0x10E4597fF93cbee194F4879f8f1d54a370DB6969'
  GNOSISLTD_GNOSIS_DISASSEMBLER_ADDRESS: '0x19414ebe07C7Eb0D5463A1E6533f6cF05e26E21e'
  GNOSISLTD_GNOSIS_ROLE: '4'
  GNOSISLTD_GNOSIS_ROLES_MOD_ADDRESS: '0x494ec5194123487E8A6ba0b6bc96D57e340025e7'
  KARPATKEY_ETHEREUM_AVATAR_SAFE_ADDRESS: '0x58e6c7ab55Aa9012eAccA16d1ED4c15795669E1C'
  KARPATKEY_ETHEREUM_DISASSEMBLER_ADDRESS: '0x8072470F155c69C0706dd6016D6720D7Eb0438Fb'
  KARPATKEY_ETHEREUM_ROLE: '1'
  KARPATKEY_ETHEREUM_ROLES_MOD_ADDRESS: '0x8C33ee6E439C874713a9912f3D3debfF1Efb90Da'
  MINIO_BUCKET: json-builder-jsons
  MINIO_ENDPOINT: minio.karpatkey.dev
