name: Build and Push to Docker Registry

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
    types:
      - opened
      - synchronize
      - reopened

  workflow_dispatch:

jobs:
  docker_build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Set SHORT_SHA as Environment Variable
        run: |
          PR_SHA=$(echo "${{ github.event.pull_request.head.sha }}" | cut -c1-7)
          echo "PR_SHA=${PR_SHA}" >> $GITHUB_ENV

      - name: Extract branch name, date and time
        shell: bash
        run: |
          echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
          echo "date=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT
          echo "time=$(date +'%H%M%S')" >> $GITHUB_OUTPUT
        id: extract_branch_d_t

      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v5
        with:
          images: registry.digitalocean.com/karpatkey/execution-app
          tags: |
            type=raw,value=pr${{ env.PR_SHA }}
            ${{ steps.extract_branch_d_t.outputs.branch }}
            ${{ steps.extract_branch_d_t.outputs.branch }}-${{ steps.extract_branch_d_t.outputs.date }}-${{ steps.extract_branch_d_t.outputs.time }}

      - name: Login to Docker
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.DOCKER_URL }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          file: ./Dockerfile
          build-args: |
            BUILDKIT_CONTEXT_KEEP_GIT_DIR=true

  deploy_pr:
    if: github.event_name == 'pull_request'
    runs-on: self-hosted
    needs: docker_build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Kubernetes
        uses: tale/kubectl-action@v1
        with:
          base64-kube-config: ${{ secrets.KUBE_CONFIG }}

      - name: Build and Deploy
        run: |
          PR_SHA=$(echo "${{ github.event.pull_request.head.sha }}" | cut -c1-7)

          cd deploy/pr-review
          ./deploy-script.sh $PR_SHA

      - name: Clean up
        run: |
          cd deploy/pr-review
          rm deployment-temp.yaml
          rm ingress-temp.yaml
