name: PR Clean up CI/CD

on:
  pull_request:
    branches:
      - develop
    types:
      - closed

jobs:
  delete-pr-deployment:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4

    - name: Set PR_SHA as Environment Variable
      run: echo "PR_SHA=$(echo ${{ github.event.before }} | cut -c1-7)" >> $GITHUB_ENV
  
    - name: Set up Kubernetes
      uses: tale/kubectl-action@v1
      with:
        base64-kube-config: ${{ secrets.KUBE_CONFIG }}

    - name: Run Deployment or Deletion Script
      run: |
        PR_SHA=$(echo ${{ github.event.before }})
        ./delete-deployment-script.sh $PR_SHA

    