name: PR CI/CD

on:
  pull_request:
    branches:
      - develop
    types:
      - opened
      - synchronize

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Kubernetes
      uses: tale/kubectl-action@v1
      with:
        base64-kube-config: ${{ secrets.KUBE_CONFIG }}

    - name: Build and Deploy
      run: |
        PR_SHA=$(echo ${{ github.event.before }})

        # Use PR_SHA in your deploy script
        ./deploy-script.sh $PR_SHA

    - name: Clean up
      run: |
        rm deployment-temp.yaml
        rm ingress-temp.yaml
